services:
  marketplace:
    container_name: marketplace
    build:
      context: ./marketplace
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    env_file:
      - ${ENV_FILE:-./marketplace/.env.container}
    environment:
      NODE_ENV: 'development'
    volumes:
      - ./marketplace:/app
      - ./marketplace/node_modules:/app/node_modules
  
  bff-marketplace-api:
    container_name: bff-marketplace-api
    build:
      context: ./bff-marketplace-api
      dockerfile: Dockerfile
      target: development
    ports:
      - "3005:3005"
    environment:
      NODE_ENV: 'development'
    volumes:
      - ./bff-marketplace-api:/app
      - ./bff-marketplace-api/node_modules:/app/node_modules