export default [
  'celular',
  'smartphone',
  'notebook',
  'tênis masculino',
  'tênis feminino',
  'camisa polo',
  'camisa social',
  'vestido',
  'calça jeans',
  'moletom',
  'jaqueta',
  'sapato masculino',
  'sapato feminino',
  'bolsa feminina',
  'relógio masculino',
  'relógio feminino',
  'óculos de sol',
  'fones de ouvido',
  'smartwatch',
  'tablet',
  'televisão',
  'videogame',
  'console de jogos',
  'jogos de videogame',
  'câmera digital',
  'impressora',
  'mouse sem fio',
  'teclado mecânico',
  'monitor',
  'cadeira gamer',
  'mesa de escritório',
  'armário',
  'sofá',
  'cama box',
  'colchão',
  'geladeira',
  'fogão',
  'micro-ondas',
  'liquidificador',
  'batedeira',
  'cafeteira',
  'aspirador de pó',
  'ventilador',
  'ar condicionado',
  'bicicleta',
  'patinete elétrico',
  'moto',
  'carro',
  'brinquedos infantis',
  'fraldas',
];
